openapi: 3.0.0
info:
  title: Mock Salesforce API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5003
paths:
  /customers:
    get:
      operationId: get_customer_details
      summary: Get Customer Details
      description: Retrieves key customer details like contact person, address, and industry from Salesforce by account name.
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
          description: The full account name of the customer.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
  /history:
    get:
      operationId: get_account_history
      summary: Get Account History
      description: Retrieves the recent activity and transaction history for a customer by their account name.
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
          description: The full account name of the customer.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object